name: gqvr
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.17
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.0
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - antialiased-cnns==0.3
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - beautifulsoup4==4.13.4
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - correlation==0.0.0
      - cycler==0.12.1
      - decord==0.6.0
      - diffusers==0.32.2
      - distro==1.9.0
      - einops==0.8.1
      - fastapi==0.116.1
      - ffmpy==0.6.1
      - filelock==3.18.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - ftfy==6.3.1
      - gdown==4.4.0
      - gradio==5.21.0
      - gradio-client==1.7.2
      - groovy==0.1.2
      - grpcio==1.74.0
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - ipdb==0.13.13
      - jinja2==3.1.6
      - jiter==0.10.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lmdb==1.7.3
      - lpips==0.1.4
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - moviepy==2.2.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - open-clip-torch==2.31.0
      - openai==1.96.1
      - opencv-python-headless==4.11.0.86
      - orjson==3.11.1
      - pandas==2.3.1
      - peft==0.14.0
      - pillow==11.3.0
      - polars==1.24.0
      - proglog==0.1.12
      - protobuf==6.31.1
      - psutil==7.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.33
      - requests==2.32.4
      - rich==14.1.0
      - ruff==0.12.7
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.7
      - starlette==0.47.2
      - sympy==1.13.1
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tifffile==2025.5.10
      - timm==1.0.15
      - tokenizers==0.21.4
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.6.0
      - torch-summary==1.4.5
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.2.0
      - typer==0.16.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - vision-aided-loss==0.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
