# general settings
name: fixed_FT_mosaic
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 310

# dataset and data loader settings
datasets:
  train:
    name: gQIR
    type: mosaic

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 24
    batch_size_per_gpu: 1

    ### ------- Training on single fixed-patch size 128x128---------
    mini_batch_sizes: [1]   
    iters: [300000]
    gt_size: 256   
    gt_sizes: [256]
    ### ------------------------------------------------------------
  val:
    name: gQIR
    type: mosaic

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 24
    batch_size_per_gpu: 1

    ### ------- Training on single fixed-patch size 128x128---------
    mini_batch_sizes: [1]   
    iters: [300000]
    gt_size: 256   
    gt_sizes: [256]
    ### ------------------------------------------------------------



# network structures
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4,6,6,8]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: BiasFree
  dual_pixel_task: False


# path
path:
  pretrain_network_g: /media/agarg54/Extreme SSD/weights/restormer/real_denoising.pth
  strict_load_g: true

# training settings
train:
  total_iter: 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean



# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: 5000
  use_tb_logger: false
  save_img: 5000
