# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: FT_mosaic_w64
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 310

datasets:
  train:
    name: gQVR
    simulation_type: mosaic

path:
  strict_load_g: true
  pretrain_network_g: /home/argar/apgi/baselines_apgi/NAFNet/pretrained_weights/NAFNet-SIDD-width64.pth


network_g:
  type: NAFNet
  width: 64
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]



# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 2000000
    eta_min: !!float 1e-7

  total_iter: 2000000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false
  use_image: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: false
  save_img: 50000

# dist training settings
# dist_params:
#   backend: nccl
#   port: 29510
